[supervisord]
nodaemon=true

[program:php-fpm]
command=/usr/local/sbin/php-fpm
autostart=true
autorestart=true
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile=/var/log/php-fpm.out.log

[program:php-server]
command=php -S 0.0.0.0:5000 -t /app
autostart=true
autorestart=true
stderr_logfile=/var/log/php-server.err.log
stdout_logfile=/var/log/php-server.out.log
